name: Deploy Worker

on:
  push:
    branches:
      - main  # Ganti dengan branch utama Anda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Atau versi Node.js lain sesuai kebutuhan

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare
        run: wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
